### ISSUE TITLE
not able to download model weights from google drive link

### ISSUE THREAD

**Issue by SudhaVinita** [bnspriyatham/Car-Damage-Classification#3]
not able to download model weights from google drive link , Please share the new link from where i can download model weights.

- [ ]

**Comment by bnspriyatham** [comment]
Sorry,

I had removed weights from Google drive due to storage issues, I will give
a Dropbox link where u can download weights for all the three models. I
will send it as soon as possible.

**Comment by bnspriyatham** [comment]
The weights file zipped and uploaded in drop box. Download it directly.
https://www.dropbox.com/s/el88tfxu1wf859w/models_weights.rar?dl=0
